### ISSUE TITLE
Timer immediately starts

### ISSUE THREAD

**Issue by mhellmeier** [alexrus/marax_timer#10]
I just set up the board and installed the reed sensor as described in the `README`.

After starting the Mara X machine and the board, the timer immediately starts counting, although the pump has not started yet. When starting or stopping the pump, the timer keeps counting and doesn't stop.

Any ideas on what causes the problem and how to fix it?

**Comment by EssayAssay** [comment]
Hi,

Make sure the switch is connected properly to the board.

If MaraX is off, does the time start counting?

**Comment by alexrus** [comment]
Hi,

Make sure the switch is connected properly to the board.

If MaraX is off, does the time start counting?

**Comment by mhellmeier** [comment]
> If MaraX is off, does the time start counting?

Yes, the timer starts even if the Mara X is off.

**Comment by rubdom** [comment]
> > If MaraX is off, does the time start counting?
> 
> Yes, the timer starts even if the Mara X is off.

Maybe the wrong kind of reed switch?  Did you buy a normally open or normally closed switch?

**Comment by mhellmeier** [comment]
> Maybe the wrong kind of reed switch? Did you buy a normally open or normally closed switch?

I bought an open switch as suggested in #7. Maybe a closed one would be correct!?

But wouldn't it then be possible to solve the problem by changing the code? Maybe be inverting all `digitalRead(PUMP_PIN)` like here
https://github.com/alexrus/marax_timer/blob/main/timer/timer.ino#L88
or here
https://github.com/alexrus/marax_timer/blob/main/timer/timer.ino#L94
?

**Comment by alexrus** [comment]
I think inverting the value should be fine ... give it a try

**Comment by mhellmeier** [comment]
Yep, inverting the value solved the problem for me!

I will create a pull request with different versions for different reed switches.
