### ISSUE TITLE
which reed sensor did you use exactly?  Mine worked for 2 days and then it stopped working.  It works when dismantled.

### ISSUE THREAD

**Issue by SvenGruhn** [alexrus/marax_timer#13]

**Comment by alexrus** [comment]
I would check other connections maybe? I used a NO sensor

**Comment by mccmax1395** [comment]
Do you have a recommendation for a specific reed sensor?  I'm trying to use [this](https://www.aliexpress.us/item/2255800342365165.html?spm=a2g0o.order_list.order_list_main.5.452d18023QvJAS&gatewayAdapt=glo2usa) one and it's constantly flipping between on and off when the pump is engaged.

**Comment by alexrus** [comment]
try this one: https://www.aliexpress.us/item/1005001309886250.html?spm=a2g0o.productlist.main.33.27c3UxnFUxnFdg&algo_pvid=bb608b83-8572-44f9-8e17-41c1e6b308c3&algo_exp_id=bb608b83-8572-44f9-8e17-41c1e6b308c3-16&pdp_npi=4%40dis%21RON%2128.44%212.35%21%21%215.94%21%21%402103241d16987791870044000ef46f%2112000015653858083%21sea%21RO%210%21AB&curPageLogUid=1fRvQ4smqTjA

**Comment by mccmax1395** [comment]
Ordered, thanks for the recommendation

**Comment by mccmax1395** [comment]
Hi just wanted to update on this for anyone else who is having this issue.  The new reed sensor had the same problem however, I found a way to fix it.  I am adapting this script into ESPHome and I fixed the problem by adding a 1 second delay to turning the bool associated to the reed sensor off.  You can find details [here](https://esphome.io/components/binary_sensor/index.html#delayed-off).  thanks for your prompt response @alexrus and for putting this repo together, it was extremely helpful.
