### ISSUE TITLE
Old version with MQTT and WiFi

### ISSUE THREAD

**Issue by borez** [alexrus/marax_timer#14]
Came back to this code, and realised the new version is significantly streamlined with no WiFi / MQTT support. Wonder if I am missing anything out?

**Comment by alexrus** [comment]
I think the mqtt version is a fork of this repo. Here it is: https://github.com/alexander-heimbuch/marax_timer

**Comment by borez** [comment]
Ah my bad, thanks!

On 13 Nov 2022, at 1:38 AM, Alex Rus ***@***.***> wrote:

﻿

I think the mqtt version is a fork of this repo. Here it is: https://github.com/alexander-heimbuch/marax_timer
