### ISSUE TITLE
Also compatible to MaraT?

### ISSUE THREAD

**Issue by janpfischer** [alexrus/marax_timer#15]
Hi all, 

thanks for this, this is looking great!
Currently I am planning to either purchase the MaraX or MaraT. The only difference I've spotted on the MaraT is that this has a PID installed. But does anyone know if the MaraT has also the 6 PIN Serial connector? Would be great to also get those readings. 

Thanks!

**Comment by alexrus** [comment]
No idea if it has the 6 pin connector
