### ISSUE TITLE
Fatal error when trying to program in Arduino IDE

### ISSUE THREAD

**Issue by hanism11** [alexrus/marax_timer#18]
I got this message when i copied the code provided and uploaded onto my Arduino board. Any help?

C:\Users\Admin\AppData\Local\Temp\.arduinoIDE-unsaved2023115-20396-10iotpg.0ay2\sketch_dec5c\sketch_dec5c.ino:7:10: fatal error: Adafruit_SSD1306.h: No such file or directory
    7 | #include <Adafruit_SSD1306.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: Adafruit_SSD1306.h: No such file or directory

**Comment by alexrus** [comment]
Please install the dependencies listed at the bottom of the page: https://github.com/alexrus/marax_timer#dependencies

**Comment by hanism11** [comment]
> Please install the dependencies listed at the bottom of the page: https://github.com/alexrus/marax_timer#dependencies

I've done that and now i've got a new error message again. I'm an absolute beginner to Arduino or any board programming so i need all the help i can get. I have only gotten this board today and are trying to program it. I however had not soldered any wires to the board.

C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\Wire\Wire.cpp:38:2: error: #error Wire library is not supported on this board
   38 | #error Wire library is not supported on this board
      |  ^~~~~
C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\Wire\Wire.cpp:56:30: error: 'SDA' was not declared in this scope
   56 | static int default_sda_pin = SDA;
      |                              ^~~
C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\Wire\Wire.cpp:57:30: error: 'SCL' was not declared in this scope; did you mean 'SCK'?
   57 | static int default_scl_pin = SCL;
      |                              ^~~
      |                              SCK

exit status 1

Compilation error: exit status 1

**Comment by alexrus** [comment]
What board is this?

**Comment by hanism11** [comment]
> What board is this?

Its an ESP8266NODEMCU board i got from Aliexpress. 

https://www.aliexpress.com/item/1005005077804800.html?spm=a2g0o.order_list.order_list_main.40.20f01802SUVEkm

**Comment by alexrus** [comment]
I think the first error is self explanatory: #error Wire library is not supported on this board

Check how you can configure the board to work with arduino app maybe?

**Comment by hanism11** [comment]
Any suggestion on a board that actually works? I really have no experience with all these.

**Comment by alexrus** [comment]
try NodeMCU V2 CP2102

**Comment by hanism11** [comment]
> try NodeMCU V2 CP2102

I shall order one and try again. Thanks!

On a side note; once i am able to program it all i need to do is upload the Time.ino code and thats all right?

**Comment by alexrus** [comment]
yes, that should be it

**Comment by hanism11** [comment]
> yes, that should be it

I tried another cable today and it worked! Managed to upload the code onto the board. Now all i need is my LCD display to test it out.

On the reed switch is there a specific way to wire it? Since it has two sides or does it not matter?

**Comment by alexrus** [comment]
it should not matter
