### ISSUE TITLE
Temperature section shoes different letters

### ISSUE THREAD

**Issue by NormanB88** [alexrus/marax_timer#8]
Hi. I followed your instructions to create a shot timer. It works create, but the temperature section shows a lot ot different letters and doesn't show the correct temperature. Sometimes it works. Mostley not. Do you have am idea whats wrong?

**Comment by NormanB88** [comment]
https://youtube.com/shorts/23GFZMBMst0?feature=share

For example

**Comment by rubdom** [comment]
> https://youtube.com/shorts/23GFZMBMst0?feature=share
> 
> For example

Try a stronger power supply. I had the same issues and that fixed it.

**Comment by NormanB88** [comment]
Holy shit. You made my day!

**Comment by NormanB88** [comment]
I Know after one hour the display shuts down, is it possible to change shut down time earlier in the code?

**Comment by alexrus** [comment]
yes, check this line: https://github.com/alexrus/marax_timer/blob/main/timer/timer.ino#L108

1000 * 60 * 60 is 1 hour in miliseconds

**Comment by JoghurtBecher-creator** [comment]
I had the same issue in the Temperature section. Different letters showing. Using a 1331 color Oled with a Modified sketch to run the Oled. Mara X Pins are D6 and D1. Using a strong enough Power Supply or the 5v directly on the Board doesnt change anything.  Any Suggestions?
